#!/bin/bash

#
# With a repo already made, push down all branches with a given base
# name (e.g. main or staging or whatever) into a new branch with just
# that name.
#

set -e

source monorepo.sh

repo="$1"
branch="$2"

cd "$repo"
pushdown "$branch"
